### ISSUE TITLE
Add Emoji Channel Picker

### ISSUE THREAD

**Issue by tregsthedev** [hackclub/toriel#155]
Let people pick specfic channels they're interested in with an emoji picker

Here's an example:
![image](https://github.com/hackclub/toriel/assets/21000033/ffdbbece-5ea5-46db-a89f-3313dae5de37)

```[tasklist]
### Tasks
- [ ] Gather list of channels we want to add
- [ ] Add them to the transcript file
- [ ] Create a new message in Transcript for this
- [ ] Figure out how to get reactions working with the Slack API
```

**Comment by karamassie** [comment]
i believe we decided this is just too much friction to joining so suggest close
